# organization name, it's used to get github repo url, also in page title
name: react-component

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       react-component
description: react-component
keywords: react-component

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - generator-rc
 - rc-server
 - rc-tools
 - rc-pager:
     repo: react-component/pager
 - rc-calendar:
     repo: react-component/calendar
 - rc-dialog:
     repo: react-component/dialog
 - rc-tabs:
     repo: react-component/tabs
 - rc-table:
     repo: react-component/table
 - rc-dropzone:
     repo: react-component/dropzone
 - rc-menu:
     repo: react-component/menu
 - rc-select:
     repo: react-component/select
 - rc-tooltip:
     repo: react-component/tooltip
 - rc-form-validation:
     repo: react-component/form-validation
 - rc-css-transition-group:
     repo: react-component/css-transition-group
 - rc-cascade-select:
     repo: react-component/cascade-select
 - rc-input-number:
     repo: react-component/input-number
 - rc-progress:
     repo: react-component/progress
 - rc-upload:
     repo: react-component/upload
 - rc-pagination:
     repo: react-component/pagination
 - rc-checkbox:
     repo: react-component/checkbox
 - rc-radio:
     repo: react-component/radio
 - rc-slider:
     repo: react-component/slider
 - rc-collapse:
     repo: react-component/collapse
 - rc-steps:
     repo: react-component/steps
 - rc-switch:
     repo: react-component/switch
 - rc-dropdown:
     repo: react-component/dropdown
 - rc-notification:
     repo: react-component/notification     
# list of maintainers, this won't be sorted
maintainers:
 - name:    YiMing He
   github:  yiminghe
   npm:     yiminghe
   twitter: yiminghe
   email:   yiminghe@gmail.com
   gittip:  yiminghe
 - name:    XiaoQing Dong
   github:  dxq613
   npm:     dxq613
   twitter: dxq613
   email:   dxq613@gmail.com
   gittip:  dxq613
 - name:    Eward Song
   github:  shepherdwind
   npm:     shepherdwind
   twitter: shepherdwind
   email:   eward.song@gmail.com
   gittip:  shepherdwind
 - name:    warmhug
   github:  warmhug
   npm:     warmhug
   twitter: warmhug
   email:   hualei5280@gmail.com
   gittip:  warmhug
 - name:    shuaiji.tsj
   github:  tsj1107
   npm:     tsj1107
   twitter: tsj1107
   email:   tsjxyz@gmail.com
   gittip:  tsj1107
 - name:    ibigbug
   github:  ibigbug
   npm:     ibigbug
   twitter: ibigbug
   email:   xiaobayuwei@gmail.com
   gittip:  ibigbug
 - name:    simaq
   github:  simaq
   npm:     simaq
   twitter: simaq
   email:   sima.zhang1990@gmail.com
   gittip:  simaq
 - name:    yuhangge 
   github:  yuhangge 
   npm:     yuhangge 
   twitter: yuhangge 
   email:   abeyuhang@gmail.com
   gittip:  yuhangge
 - name:    sliuqin 
   github:  sliuqin 
   npm:     sliuqin 
   twitter: sliuqin 
   email:   sliuqin@gmail.com
   gittip:  sliuqin
 - name:    jljsj33 
   github:  jljsj33 
   npm:     jljsj33 
   twitter: jljsj33 
   email:   155259966@qq.com
   gittip:  jljsj33
# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
