# organization name, it's used to get github repo url, also in page title
name: react-component

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       react-component
description: react-component
keywords: react-component

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - generator-rc
 - rc-server
 - rc-pager:
     repo: react-component/pager
 - rc-calendar:
     repo: react-component/calendar
 - rc-dialog:
     repo: react-component/dialog
 - rc-tabs:
     repo: react-component/tabs
 - rc-table:
     repo: react-component/table

# list of maintainers, this won't be sorted
maintainers:
 - name:    YiMing He
   github:  yiminghe
   npm:     yiminghe
   twitter: yiminghe
   email:   yiminghe@gmail.com
   gittip:  yiminghe


# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has